name: get
on: 
  schedule:
    - cron: '0/10 * * * *'
  push:
    branches: 
      - main

jobs:
  dos:
    runs-on: ubuntu-latest

    steps:
    - name: install GO
      uses: actions/setup-go@v2.1.4
      
    - name: run it
      run: |
        git clone https://github.com/thun888/lab.git
        cd lab
        go run main.go
        go run main.go
        go run main.go
        go run main.go
        go run main.go
        go run main.go
        go run main.go
        go run main.go
        go run main.go
        go run main.go
        go run main.go
