name: get
on: 
  schedule:
    - cron: '0/10 * * * *'
  push:
    branches: 
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: install GO
      uses: actions/setup-go@v2.1.4
      
    - name: run it
      run: |
        ls
        go run main.go
